[DRAFT] Add ICAROS Python Bindings
personalrobotics/libada pull request #48
Opened 2021-02-28 03:42 UTC by sniyaz

Don't review yet, just creating this for others to look at!
***

**Before creating a pull request**

- [ ] Document new methods and classes
- [ ] Format code with `make format`

**Before merging a pull request**

- [ ] Add unit test(s) for this change

2021-03-04 19:42 UTC, hejia-zhang approved these changes
Looks good!

2021-03-04 20:56 UTC, hejia-zhang commented on src/adapy/ada_py.cpp
> +          "compute_retime_path",
compute_retime_path shoudn't accept spline trajectory based on the current KunzeRetimer implementation. It seems it only accepts aikido::trajectory::Interpolated now.

2021-03-04 21:00 UTC, hejia-zhang commented on src/libada/Ada.cpp
> +  auto timedTrajectory = std::move(
In ComputeJointSpacePath, we also retime the trajectory, so maybe we can rename the function as computeRetimedJointSpacePath?

2021-03-04 21:06 UTC, hejia-zhang requested changes
1. We could probably rename ComputeJointSpacePath as ComputeRetimedJointSpacePath? 2. We could change the compute_retime_path function to only accept aikido::trajectory::Interpolated typed trajectory? 
I have tested this branch with another lab assignment code and it works great!

2021-03-08 17:48 UTC, brianhou requested changes
I mostly have some quick high-level questions:

- Would it make sense to move `src/adapy` to a top-level `adapy` directory or `python/adapy`? Otherwise, the layout of `src` and `include` no longer match our other repos. (`python/adapy` would match `python/aikidopy`; it might also then make sense to move the Python scripts into, say, `python/tests`.)
- Should we organize this PR into two? One with actual `libada` changes, one with bindings.
- Do bindings need to be defined as C++ lambda expressions? I feel like this would be way more readable if, say, we explicitly named the `create_ik` function and then did all the module `m.def` stuff with those named functions.

2021-03-08 17:48 UTC, brianhou commented on CMakeLists.txt
> +find_package(Boost REQUIRED python)
Is this used?

2021-03-08 17:48 UTC, brianhou commented on CMakeLists.txt
> +find_package(PythonInterp ${ADAPY_PYTHON_VERSION} REQUIRED)
I wonder whether this can be pulled into a CMake module, similar to how @egordon created one for ClangFormat: https://github.com/personalrobotics/aikido/pull/509.

2021-03-08 17:50 UTC, brianhou commented
Also, you mentioned that you had some significant challenges with getting this to build, so I think it would make sense to preserve that knowledge in a README.

2021-03-12 04:48 UTC, egordon commented on CMakeLists.txt
> +find_package(PythonInterp ${ADAPY_PYTHON_VERSION} REQUIRED)
Forking into a separate issue #49

2021-03-12 04:53 UTC, egordon commented on CMakeLists.txt
> +find_package(Boost REQUIRED python)
Nope, removed.

2021-03-12 05:38 UTC, sniyaz commented
> Also, you mentioned that you had some significant challenges with getting this to build, so I think it would make sense to preserve that knowledge in a README.

@brianhou Sorry is this comment directed at me or at @egordon?

2021-03-12 06:57 UTC, brianhou commented
> > Also, you mentioned that you had some significant challenges with getting this to build, so I think it would make sense to preserve that knowledge in a README.
> 
> @brianhou Sorry is this comment directed at me or at @egordon?

I thought this was you @sniyaz

2021-03-12 08:11 UTC, sniyaz commented
> > > Also, you mentioned that you had some significant challenges with getting this to build, so I think it would make sense to preserve that knowledge in a README.
> > 
> > @brianhou Sorry is this comment directed at me or at @egordon?
> 
> I thought this was you @sniyaz --  something about different versions, maybe?

@brianhou ah, yes- I actually think setting 20.04 as the default solves those issues (given that the default pybind11 version is more than sufficient, unlike on 20.04)

2021-03-15 22:45 UTC, brianhou requested changes

2021-03-15 22:45 UTC, brianhou commented on CMakeLists.txt
> +  src/libada/AdaFingerKinematicSimulationPositionCommandExecutor.cpp
I think this intermediate `libada` directory should be removed now?

2021-03-15 22:45 UTC, brianhou commented on CMakeLists.txt
> +    python/adapy/adapy.cpp
This naming scheme is somewhat unpleasant to me: these are all already in `python/adapy`, so is it necessary to have the `_py` suffixes? I assume these can be imported later as, e.g. `adapy.ada`, `adapy.aikido`, etc.

2021-03-15 22:45 UTC, brianhou commented on CMakeLists.txt
> +    ${libaikidopy_LIBRARIES}
I haven't looked closely; is `libaikidopy` actually defined?

2021-03-15 22:45 UTC, brianhou commented on python/adapy/aikido_py.cpp
> +            dart::utils::DartLoader urdfLoader;
I would recommend calling `aikido::io::loadSkeletonFromURDF`, rather than duplicating its logic here.

2021-03-15 22:45 UTC, brianhou commented on python/adapy/aikido_py.cpp
> +            dart::utils::DartLoader urdfLoader;
Same as above.

2021-03-15 22:45 UTC, brianhou commented on python/adapy/aikido_py.cpp
> +            if (i + 1 <= int(self->getNumSkeletons()))
```suggestion
            if (i < int(self->getNumSkeletons()))
```

2021-03-15 22:45 UTC, brianhou commented on python/adapy/aikido_py.cpp
> +            if (i + 1 <= int(self->getNumSkeletons()))
Actually, I think this is already handled by `World::getSkeleton`.

2021-03-15 22:45 UTC, brianhou commented on python/adapy/aikido_py.cpp
> +            armSpace->setState(armSkeleton.get(), currentState);
Does `MetaSkeletonStateSaver` help?

2021-03-15 22:45 UTC, brianhou commented on python/adapy/ik_py.cpp
> +            if (!sampled)
This seems somewhat suspicious -- doesn't `positions` contain garbage? How can the user tell?

2021-03-15 22:45 UTC, brianhou commented on python/adapy/pr_tsr_py.cpp
> +            auto Trans = self->mTw_e.matrix();
Same as above.

2021-03-15 22:45 UTC, brianhou commented on python/tests/simple_trajectories.py
> +from moveit_ros_planning_interface._moveit_roscpp_initializer import roscpp_init
I'd suggest running a quick linter on these Python files. For one, imports should be at the top of the file.

2021-03-15 22:45 UTC, brianhou commented on python/tests/simple_trajectories.py
> +    traj_rev = ada.compute_joint_space_path(arm_state_space, waypoints_rev)
```suggestion
    waypoints = [positions, positions2, positions3, positions4]
    traj = ada.compute_joint_space_path(arm_state_space, enumerate(waypoints))
    traj_rev = ada.compute_joint_space_path(arm_state_space, enumerate(waypoints[::-1]))
```

2021-03-15 22:45 UTC, brianhou commented on python/adapy/pr_tsr_py.cpp
> +            return Trans;
Why not just return these directly?

```suggestion
            return self->mT0_w.matrix();
```

2021-03-15 22:45 UTC, brianhou commented on python/adapy/pr_tsr_py.cpp
> +            self->mT0_w = transform;
Why not set these directly?
```suggestion
            self->mT0_w = matrixToIsometry(pose);
```

2021-03-15 22:45 UTC, brianhou commented on python/adapy/pr_tsr_py.cpp
> +            auto transform = matrixToIsometry(pose);
Same as above.

2021-03-15 22:45 UTC, brianhou commented on python/tests/simple_trajectories.py
> +    pdb.set_trace()
Are these supposed to be here?

2021-03-15 22:45 UTC, brianhou commented on python/tests/simple_trajectories.py
> +    preshape = [1.1, 1.1]
Unused.

2021-03-15 22:54 UTC, egordon commented on CMakeLists.txt
> +    ${libaikidopy_LIBRARIES}
Doesn't look like it, removing.

2021-03-15 22:57 UTC, egordon commented on CMakeLists.txt
> +    python/adapy/adapy.cpp
These names have no effect on importing, as all objects are placed directly under the adapy module. E.g., the Ada object is imported as `adapy.Ada`.

I can see the benefit of the _py suffix in terms of searching in a text editor. Say, differentiating ada_py.cpp (the python bindings) from Ada.cpp (the base class).

2021-03-15 23:37 UTC, brianhou commented on CMakeLists.txt
> +    python/adapy/adapy.cpp
Hmm, maybe `ada_bindings.cpp`, etc. then?

2021-03-15 23:52 UTC, egordon commented on python/adapy/ik_py.cpp
> +            if (!sampled)
Default constructor for a dynamically-sized Eigen vector initializes the vector to length 0 (no coefficients), so there is no garbage to initialize. It should end up as an empty (len = 0) numpy array.
See: https://eigen.tuxfamily.org/dox/group__TutorialMatrixClass.html under "Constructors"

2021-03-15 23:52 UTC, egordon commented on python/adapy/ik_py.cpp
> +            if (!sampled)
Added a comment clarifying this behavior.

2021-03-15 23:57 UTC, egordon commented on python/tests/simple_trajectories.py
> +    pdb.set_trace()
Yep, was used as built-in break points during the test (analogous to our "waitForUser")

A little inelegant, can create another issue for it.

2021-03-16 00:17 UTC, egordon commented on python/tests/simple_trajectories.py
> +    traj_rev = ada.compute_joint_space_path(arm_state_space, waypoints_rev)
Unfortunately, this doesn't work. enumerate() creates int types, but the pybind11 converter expects float types.

We could loop and make them floats, but I think it is easier in this case to show the specifics, especially if somebody is looking at this to figure out how the API works.

2021-03-16 00:22 UTC, egordon commented on python/adapy/aikido_py.cpp
> +            armSpace->setState(armSkeleton.get(), currentState);
Not sure how to use it, @sniyaz or @brianhou have any examples? Otherwise I'll puzzle it out.

2021-03-16 00:26 UTC, brianhou commented on python/adapy/aikido_py.cpp
> +            armSpace->setState(armSkeleton.get(), currentState);
Here's an example: https://github.com/personalrobotics/aikido/blob/master/src/planner/dart/ConfigurationToConfiguration_to_ConfigurationToTSR.cpp#L54

To be clear, it may not actually be useful to do here, but in principle it should help with automatically restoring the `MetaSkeleton` positions.

2021-03-16 00:40 UTC, brianhou commented on python/tests/simple_trajectories.py
> +    traj_rev = ada.compute_joint_space_path(arm_state_space, waypoints_rev)
Huh. That's somewhat unpleasant that it isn't automatically converted, but good to know!

2021-03-16 01:23 UTC, brianhou reviewed
> Do bindings need to be defined as C++ lambda expressions? I feel like this would be way more readable if, say, we explicitly named the `create_ik` function and then did all the module `m.def` stuff with those named functions.

I'm willing to accept the changes as is for now, but I still feel like this would be better.

2021-03-16 01:58 UTC, egordon commented on python/tests/simple_trajectories.py
> +    traj_rev = ada.compute_joint_space_path(arm_state_space, waypoints_rev)
I think it is a combo if it being double-nested (std::pair inside std::vector) and the fact that pybind11 may not support std::pair as well as it supports std::vector.

2021-03-19 12:06 UTC, sniyaz commented
An update: I've (**finally**) managed to get my dev box set up with 20.04 + Noetic. I can confirm that from a fresh, standard machine install everything works fine. The pybind11 version is more than sufficient and everything works great in sim :)

I'm going to work on some more of this feedback from @brianhou now that I have the new env set up and working :smiley:

2021-03-28 05:20 UTC, sniyaz commented
@brianhou and others, I've responded to the lambda feedback and cleaned up a few other things. I think we're ready for a final review?

I wasn't sure whether to use camel case for the named methods since that seemed a little confusing, but happy to change it if we want :)

2021-03-31 16:39 UTC, hejia-zhang approved these changes
It looks good!

2021-04-01 22:40 UTC, egordon commented
Everything still runs perfectly on the real bot. Merging as admin past the Travis checks. Good job all!

2021-04-01 22:40 UTC, merged