Add gen3 6dof controller config and launch instructions
personalrobotics/libada pull request #61
Opened 2021-09-09 21:43 UTC by madan96

This adds the controller yaml file for gen3 6dof arm and also updates the `default.launch` file with additional arguments and node required for `kortex_hardware`.
***

**Before creating a pull request**

- [ N/A ] Document new methods and classes
- [ N/A ] Format code with `make format`

**Before merging a pull request**

- [ N/A ] Add unit test(s) for this change

2021-09-09 21:43 UTC, madan96 commented
Currently, we launch all the different controllers (including `group_joint_velocity_controller` for both gen2 and gen3. This will result in errors for the controllers that haven't been configured properly. Should we use conditionals until gen3 supports all of them?

2021-09-09 22:44 UTC, egordon requested changes
Happy to approve once the minor comments are addressed (mostly the controller loading, since this file needs to work with both Gen2 and Gen3 at all times).

2021-09-09 22:44 UTC, egordon commented on launch/default.launch
> +  <arg name="ip_address" default="132.236.20.28" doc="IP address for TCP/UDP comms"/>
I would add a line break here and a docstring making clear that these are the Gen3-specific arguments.

2021-09-09 22:44 UTC, egordon commented on launch/default.launch
>     <rosparam file="$(find libada)/config/gen$(arg version)_$(arg dof)dof.yaml" command="load" />
For right now, you can have 2 separate commands cordoned off by version.

Make sure that all controllers you have running for a given version actually work and won't throw a bunch of errors being initialized (I'm not sure if, say, you don't have an effort interface, whether you can init the effort controller stopped without erroring out).

As a note: in the future, Aikido's Robot (specifically, a RosRobot subclass) will have the ability to load the controllers directly (using the YAML as a guide), potentially removing the need for spawning them here.

2021-09-13 17:10 UTC, egordon approved these changes
Looks good, thank you!
FYI: Make sure to re-request review when it is ready.

2021-09-13 17:10 UTC, merged

2021-09-13 17:13 UTC, madan96 commented
Oh! I actually wanted to test it out one last time. I'll just test the `master` I guess.