Build on simplified robot API
personalrobotics/libada pull request #64
Opened 2021-09-15 23:39 UTC by egordon

[Describe this pull request. Link to relevant GitHub issues, if any.]
Prerequisite: https://github.com/personalrobotics/aikido/pull/593

Makes required changes (with minimal interface changes) to match the new simplified Robot API.
***

**Before creating a pull request**

- [ ] Document new methods and classes
- [ ] Format code with `make format`

**Before merging a pull request**

- [ ] Add unit test(s) for this change

2021-10-05 22:01 UTC, amalnanavati commented on include/libada/detail/Ada-impl.hpp
> -bool Ada::moveArmToTSR(
Hmm, it seems liek `moveArmToTSR` was removed from both Ada.hpp and Ada-impl.hpp. What is the replacement function for planning to a TSR (which is heavily used in `ada_feeding`)?

2021-10-05 22:03 UTC, amalnanavati commented on launch/default.launch
> +  <arg name="ip_address" default="emprise-kortex.coecis.cornell.edu" doc="IP address for TCP/UDP comms"/>
Is this something we want to include in the public GitHub files? It seems very lab-specific. (I'm fine either way, just wanted to flag it in case it got pushed by mistake)

2021-10-06 00:47 UTC, egordon commented on include/libada/detail/Ada-impl.hpp
> -bool Ada::moveArmToTSR(
See the base Robot class interface (https://github.com/personalrobotics/aikido/blob/master/include/aikido/robot/Robot.hpp)

We have `planToTSR`, which returns a trajectory, followed by `executeTrajectory`. This is how the new interface works.

2021-10-07 23:45 UTC, amalnanavati commented on include/libada/detail/Ada-impl.hpp
> -bool Ada::moveArmToTSR(
Makes sense, thanks. But I guess my core question is: do we want to change `ada_feeding` to do two-step `planToTSR` and `executeTrajectory`, or would we rather just provide a `moveArmToTSR` function in libada that does those two steps? If we do the latter, there will be fewer required changes in `ada_feeding` to adapt to this new interface. And it may also be beneficial to avoid copy-pasting code, given how often `moveArmToTSR` is called in `ada_feeding`.

2021-10-08 23:07 UTC, amalnanavati commented on include/libada/Ada.hpp
> +  /// \param[in] confNamespace rosparam naemspace of configuration object.
Typo: namespace

2021-10-08 23:11 UTC, amalnanavati commented on src/Ada.cpp
> +  if (providedUri.toString() != "file://")
Should this instead be some kind of "starts with" function? Because I imagine any URI that overrides the feault would not just be "file://", but rather would start with that.

2021-10-08 23:16 UTC, amalnanavati commented on include/libada/Ada.hpp
> +      const dart::common::Uri& adaSrdfUri = dart::common::Uri(""),
At a minimum, if there is a use case, the comment describe why we have these additional params when they are already in the rosparam file. I for one was confused to see these, and see them default to "", given that they are specified in the rosparam file.

2021-10-08 23:31 UTC, amalnanavati commented on launch/simulation.launch
> +  <rosparam file="$(find libada)/config/gen$(arg version)_$(arg dof)dof.yaml" command="load" />
It looks like arg version and arg dof are missing from this launchfile

2021-10-08 23:38 UTC, amalnanavati commented on python/adapy/ada_bindings.cpp
> +dart::dynamics::BodyNode* get_endeffector_body_node(ada::Ada::AdaHand* self)
Small thing (no need to change) but in the C++ camelCase, "end" and "effector" are treated as different words, but in the Python underline nomenclature, they are treated as one word. No need to change it if there is already code that uses the function as-is

2021-10-08 23:39 UTC, amalnanavati commented on python/adapy/ada_bindings.cpp
> +          "bodies if left blank)",
jw, why does this function get/need a descriptor and not the rest?

2021-10-08 23:45 UTC, amalnanavati commented on python/tests/test_collisions.py
> +input("Press Enter to Continue")
What is the rationale for keeping this in the pushed code? Requiring user input could hinder running the tests in the background, and I couldn't notice any reason for it (e.g., requiring users to do something before the test continues).

2021-10-08 23:45 UTC, amalnanavati commented on python/tests/test_collisions.py
> +input("Press Enter to Continue")
Same for the other input(s) in this file

2021-10-08 23:46 UTC, amalnanavati commented on resources/g2_6d_named_configs.yaml
> +    almost_closed: [1.1, 1.1]
Small nit: For consistency, perhaps rename this to `partial_closed`?

2021-10-08 23:47 UTC, amalnanavati commented on resources/g2_6d_named_configs.yaml
> +    almost_closed: [1.1, 1.1]
Actually nvm, it isn't clear what the difference between "partial_open" and "partial_closed" is. "almost_closed" is clearer.

2021-10-08 23:50 UTC, amalnanavati commented on include/libada/detail/Ada-impl.hpp
> +  // See if the passed-in values aree valid or not
Typo: are

2021-10-08 23:52 UTC, amalnanavati commented on include/libada/detail/Ada-impl.hpp
> +                   != mArm->getMetaSkeleton()->getNumDofs());
I might need to dig a bit deeper, but in what scenarios would `mMetaSkeleton` be different from `mArm->getMetaSkeleton()`? This seems redundant on first glance

2021-10-09 00:07 UTC, amalnanavati commented on include/libada/detail/Ada-impl.hpp
> +                   != mArm->getMetaSkeleton()->getNumDofs());
Further if `mArm->getMetaSkeleton()`'s DOFs must necessarily equal `mMetaSkeleton `'s DOFs, shouldn't that be checked when these variables are set, as opposed to now?

2021-10-09 00:08 UTC, amalnanavati commented on include/libada/detail/Ada-impl.hpp
> +                                     != mArm->getMetaSkeleton()->getNumDofs());
Same comment about the two metaskeletons

2021-10-09 00:41 UTC, amalnanavati commented on src/Ada.cpp
> +  setTrajectoryExecutor(nullptr);
I didn't see any documentation in AIKIDO Robot.hpp that specifies the behavior of this function with a nullptr. Could you maybe add that to the comment here?

2021-10-09 00:48 UTC, amalnanavati commented on src/Ada.cpp
> +  createTrajectoryExecutor(true);
Small nit: for both of these, it seemed really strange to be that the name of the trajectory controller wasn't passed as a parameter to `createTrajectoryExecutor`, and instead was set before the function was called. After a lot of thinking about it, I couldn't identify a strictly better way to do it, but maybe this can be clarified by adding a comment like: "load the arm trajectory controller name and create the executor"? It is a small thing but I feel like it would help make this section a lot more readable/intuitive

2021-10-09 00:54 UTC, amalnanavati commented on src/Ada.cpp
> +  return mHand->executePreshape("closed");
Is it worthwhile to also add corresponding functions for partially open and almost closed? (I'm not sure if that would be used -- just wondering since those are also provided by the yaml)

2021-10-09 01:00 UTC, amalnanavati requested changes
Mostly looks good. One change needs to be addressed (arg version in the simulation launchfile), and the other particularly important comment is the discussion about `moveArmToTSR` imo. The other comments are small nits/typos/clarifications.

LMK when I should re-review (will likely be an easy approval)

2021-10-11 17:41 UTC, hsnemlekar submitted a review, later dismissed
Review comments (including those by Amal) before merging. For icaros, the only concern is the python bindings for Ada taking only bool as argument.

2021-10-11 17:41 UTC, hsnemlekar commented on python/adapy/ada_bindings.cpp
> +        return std::make_shared<ada::Ada>(simulation);
Looks like the pythonic implementation of Ada only takes the bool argument and not the rest.

2021-10-14 06:25 UTC, amalnanavati commented
FYI, the parameters for Ada() are differently ordered in this branch than in the [RKJenamani/gen3-integration](https://github.com/personalrobotics/libada/blob/ed6483f4ba1e34d8e09988f13f6946a66868f828/include/libada/Ada.hpp#L101) branch. However, ada_feeding's [emprise/gen3-integration](https://github.com/personalrobotics/ada_feeding/blob/4d703b3636aa18b32287ab38e8003207aaf2b90a/src/FeedingDemo.cpp#L55) branch builds off of the RKJenamani/gen3-integration branch of libada. Further, for consistencies sake it would be easier if gen2 and gen3 use the same parameter ordering. Therefore, **I'd suggest we change the order of Ada() parameters in this branch to the order in the [RKJenamani/gen3-integration](https://github.com/personalrobotics/libada/blob/ed6483f4ba1e34d8e09988f13f6946a66868f828/include/libada/Ada.hpp#L101) branch**.

2021-11-18 22:15 UTC, egordon commented on include/libada/detail/Ada-impl.hpp
> -bool Ada::moveArmToTSR(
As this has been addressed in the `ada_feeding` PR, I think it makes sense to leave it as-is.

2021-11-18 22:17 UTC, egordon commented on launch/default.launch
> +  <arg name="ip_address" default="emprise-kortex.coecis.cornell.edu" doc="IP address for TCP/UDP comms"/>
Thank you for pointing this out. I think this is fine to leave in (and is in fact better than the IP address, which I think is more sensitive than the DNS record), since EmPRISE is right now the only lab that uses ADA on Gen3.

It also demonstrates that this value can be either an IP address OR a DNS name.

2021-11-18 22:20 UTC, egordon commented on src/Ada.cpp
> +  if (providedUri.toString() != "file://")
This is to detect a URI constructed from an empty string, which defaults to "file://".

If the URI was constructed from an empty string, then use the default. Else use the override.

I'll add a comment explaining this.

2021-11-18 22:28 UTC, egordon commented on include/libada/Ada.hpp
> +      const dart::common::Uri& adaSrdfUri = dart::common::Uri(""),
That's fair. Given that we already require an `adaConf` rosparam object and we already have a way to override it in the feeding demo, these parameters are not necessary. I'll remove them and update the ada_feeding Pr accordingly.

2021-11-18 22:30 UTC, egordon commented on src/Ada.cpp
> +  if (providedUri.toString() != "file://")
Actually, removing the args below also removes this issue.

2021-11-18 22:31 UTC, egordon commented on launch/simulation.launch
> +  <rosparam file="$(find libada)/config/gen$(arg version)_$(arg dof)dof.yaml" command="load" />
Already addressed.

2021-11-18 22:32 UTC, egordon commented on python/adapy/ada_bindings.cpp
> +dart::dynamics::BodyNode* get_endeffector_body_node(ada::Ada::AdaHand* self)
No use that I could find. Changing. @hsnemlekar keep this in mind.

2021-11-18 22:35 UTC, egordon commented on python/adapy/ada_bindings.cpp
> +          "bodies if left blank)",
This is a brand new function that I added. Hence I added it with a description.

All these functions should have a description. For another PR, added as issue #70

2021-11-18 22:38 UTC, egordon commented on python/tests/test_collisions.py
> +input("Press Enter to Continue")
This is not meant be a scripted unit test. This is designed to be code run synchronously by a user in the foreground to both demonstrate how collision checking works, and function as a sort of integration test. The `input`s give time for the user to open Rviz and see the configuration of the robot.

2021-11-18 22:38 UTC, egordon commented on python/tests/test_collisions.py
> +input("Press Enter to Continue")
I've changed the folder to `scripts` to make this more clear.

2021-11-18 22:43 UTC, egordon commented on include/libada/detail/Ada-impl.hpp
> +                   != mArm->getMetaSkeleton()->getNumDofs());
mMetaSkeleton is the *entire* robot, arm and gripper. While `mArm->getMetaSkeleton()` is *only* the arm (no gripper DoFs).

So this function allows velocity/acceleration limits to be passed in for either the entire robot, OR only the arm portion (excluding the gripper). Hence the failure if the size of the vector is both != robotDoFs AND != armDoFs. (DeMorgan's Law)

The number of DoFs are never equal, as mMetaSkeleton DoFs > mArm DoFs.

2021-11-18 22:43 UTC, egordon commented on include/libada/detail/Ada-impl.hpp
> +                                     != mArm->getMetaSkeleton()->getNumDofs());
See above reply.

2021-11-18 22:46 UTC, egordon commented on src/Ada.cpp
> +  setTrajectoryExecutor(nullptr);
This function is a clean setter. Whatever is called here, is set as mTrajectoryExecutor. No null checks or extra functionality are performed here.

Added a comment.

2021-11-18 22:48 UTC, egordon commented on src/Ada.cpp
> +  createTrajectoryExecutor(true);
Updated comments to better explain what's going on.

2021-11-18 22:50 UTC, egordon commented on src/Ada.cpp
> +  return mHand->executePreshape("closed");
No need I think. There is nothing to prevent the user from calling ada->getHand()->executePreshape("almost_closed").

These utility functions are here to maintain the previous interface.

And those other preshapes are kept in the YAML mostly because there is no reason to remove them.

2021-11-19 20:20 UTC, amalnanavati commented on include/libada/detail/Ada-impl.hpp
> -bool Ada::moveArmToTSR(
Agreed

2021-11-19 20:26 UTC, amalnanavati commented on include/libada/detail/Ada-impl.hpp
> +                   != mArm->getMetaSkeleton()->getNumDofs());
This clarification helps a lot! So basically we automatically detect whether the limits are for the entire robot or the arm based on the num dofs in the limit, and then apply it to that skeleton. Makes sense, thanks!

2021-11-19 20:35 UTC, amalnanavati approved these changes
LGTM. 

(FYI, for this review I focused on the comments and the commits since merging the RKJenamani branch, since I already reviewed and approved the RKJenamani PR)

2021-11-19 21:56 UTC, merged