Added Camera Self-Calibration for Gen2
personalrobotics/libada pull request #67
Opened 2021-10-21 23:37 UTC by amalnanavati

[Describe this pull request. Link to relevant GitHub issues, if any.]

Adds dynamic camera self-calibration using an AprilTag that is attached to the robot and within the camera's field-of-view.

***

**Before creating a pull request**

- [ ] Document new methods and classes
- [ ] Format code with `make format`

**Before merging a pull request**

- [ N/A ] Add unit test(s) for this change

2021-10-21 23:38 UTC, amalnanavati commented
TODO: Add documentation and run `make format`

2021-10-21 23:40 UTC, amalnanavati commented on config/gen2_6dof.yaml
> +    tag_threads:       2          # default: 2
Do we want to expose all of these? They are `apriltag_ros` params that I kept at the default values

2021-10-21 23:59 UTC, egordon commented on launch/default.launch
>    <group if="$(arg use_forque)">
Keep it in use_forque for now because it is a bit feeding-dependent, since the AprilTag is mounted on the forque apparatus.

The perception pipeline right now is only relevant for the food/face detection.

Arguably, I think all the stuff under perception here should be moved to `ada_feeding` (since it is only food and face detection).

2021-10-22 00:10 UTC, egordon requested changes
Wonderful low-hanging fruit, thank you! Comments on how to organize this, but this was 100% needed, and I'm excited to get it merged!

2021-10-22 00:10 UTC, egordon commented on config/gen2_6dof.yaml
> +    child_frame: "camera_link"
See other comment, let's add this default transform if the user decides against using AprilTag calibration.

Additionally: I think better behavior would be to default to the `last-detected` transformation rather than this default parameter (except on start-up).

2021-10-22 00:10 UTC, egordon commented on scripts/camera_calibration_tag.py
> +        rate.sleep()
Add newline

2021-10-22 00:10 UTC, egordon commented on launch/default.launch
> +    <!-- This transform specifies where the center of the tag is relative to the robot. The rotation should be such that looking straight at the tag (oriented correctly), x is right, y is up and z is
To build on other comments: let's surround this in another argument, say, `use_apriltag_calib`. And use the default static transform otherwise.

Additionally, I would add the ability to run the apriltag calibration code in a non-online form as a calibration procedure in-and-of-itself. i.e. detect the april tag for 60 frames and then record/print the average transform.

2021-12-14 00:33 UTC, amalnanavati commented
Merged in master. This PR has no dependencies, so is ready to be merged in once it is approved. @egordon should be a quick re-review.

2022-01-07 22:24 UTC, egordon approved these changes
LGTM, I'll merge.

2022-01-07 22:24 UTC, merged