Update Launch Files for Smoother Workflow
personalrobotics/libada pull request #81
Opened 2022-11-26 23:58 UTC by egordon

See updated readme.

This utilizes proper `.launch` hierarchies. With a small base launch file matching the repo name, and sub-launch files to configure different components of the system (either Gen3 or Gen2).

Also added properly forwarded arguments to `jaco_hardware`.

***

**Before creating a pull request**

- [ N/A ] Document new methods and classes
- [ N/A ] Format code with `make format`

**Before merging a pull request**

- [ N/A ] Add unit test(s) for this change

2022-11-30 02:16 UTC, amalnanavati commented on README.md
> +Clone all of the above into your catkin workspace and build with `catkin build`. Most recently tested on ROS Noetic, Ubuntu 20.04 LTS.
Not crucial for this PR, but eventually we should consider adding a [pr-rosinstall](https://github.com/personalrobotics/pr-rosinstalls) for this.

2022-11-30 02:17 UTC, amalnanavati commented on README.md
> +**Arguments**:
Nit, but could you add the default arguments to this readme?

2022-11-30 02:22 UTC, amalnanavati approved these changes
Great improvement for readability and ease-of-use of the code :)

2022-12-01 00:19 UTC, hsnemlekar requested changes
Just the changes for the dependencies in the README if they are required. Otherwise looks good to merge.

2022-12-01 00:33 UTC, egordon commented on config/gen2_6dof_controllers.yaml
> -move_until_touch_topic_controller:
This is a feeding-specific controller (since the FT sensor is used in the forque). Sot it was moved to `ada_feeding`.

2022-12-01 00:39 UTC, egordon commented
Note @hsnemlekar if a merge looks okay to merge except for Nits, it is better to leave as a comment, as "requesting changes" blocks the merge. I can dismiss as an admin, but not the best practice.

2022-12-01 17:18 UTC, amalnanavati approved these changes

2022-12-01 17:21 UTC, hsnemlekar approved these changes

2022-12-01 17:48 UTC, merged